CREATE TABLE if NOT EXISTS uncharblog.grid_table (
op text,
vis text,
news_heat text,
quantity INTEGER,
secur text,
side text,
status text,
lmt_pr DOUBLE PRECISION,
tif text,
fill_qty INTEGER,
avg_pr DOUBLE PRECISION,
filled DOUBLE PRECISION,
working_qty INTEGER,
idle INTEGER,
data_export_restricted text,
last_update DATE,
create_time DATE,
vwap DOUBLE PRECISION,
data_export_restricted_2 text,
col_last DOUBLE PRECISION,
bid DOUBLE PRECISION,
ask DOUBLE PRECISION,
volume INTEGER,
d_adv DOUBLE PRECISION,
UNIQUE (op, vis, news_heat, quantity, secur, side, status, lmt_pr, tif, fill_qty, avg_pr, filled, working_qty, idle, data_export_restricted, last_update, create_time, vwap, data_export_restricted_2, col_last, bid, ask, volume, d_adv)
);
